  // v21: optional collections and local trip plans. No remote pairing is simulated.
  let collectionMode='feed',activeCollectionId=null,collectionSection='계획',tripDay=null,collectionDraft=null,stopDraft=null,formCollectionContext=null,linkContext=null;
  const collectionsV21=()=>state.collections||[];
  const collectionByIdV21=n=>collectionsV21().find(c=>c.id===Number(n));
  function daysV21(start,end){if(!validISODate(start)||!validISODate(end)||end<start)return[];const a=Date.parse(start+'T12:00:00Z'),b=Date.parse(end+'T12:00:00Z'),n=Math.round((b-a)/86400000)+1;if(n>31)return[];return Array.from({length:n},(_,i)=>new Date(a+i*86400000).toISOString().slice(0,10));}
  function safeLinkV21(raw){if(!raw)return '';try{const u=new URL(raw);if(raw.length>2000||u.href.length>2000||u.protocol!=='https:'||u.username||u.password)return null;return u.href;}catch{return null;}}
  function linkedItemsV21(c){return{posts:state.posts.filter(p=>p.collectionId===c.id),events:state.events.filter(v=>v.collectionId===c.id&&!isHiddenFromMe(v)),tasks:allTasks().filter(x=>x.task.collectionId===c.id)};}
  function collectionPhotosV21(c){return linkedItemsV21(c).posts.flatMap(p=>(p.media?.length?p.media:p.photoUrl?[p.photoUrl]:[]).map((url,i)=>({url,p,index:i})));}
  function collectionNavV21(){return '<nav class="v21-nav" aria-label="덤프 보기"><button aria-current="'+(collectionMode==='feed'?'page':'false')+'" onclick="OD.collectionsFeed()">피드</button><button aria-current="'+(collectionMode!=='feed'?'page':'false')+'" onclick="OD.collections()">모음'+(collectionsV21().length?'<small>'+collectionsV21().length+'</small>':'')+'</button></nav>';}
  function collectionHeaderV21(){return header('덤프').replace('aria-label="덤프 작성" onclick="OD.post()"','aria-label="'+(collectionMode==='list'?'모음 만들기':'모음에 추가')+'" onclick="OD.'+(collectionMode==='list'?'collectionForm()':'collectionAdd()')+'"');}
  function collectionEmptyV21(title,desc,action=''){return '<div class="v21-empty">'+icon('grid')+'<strong>'+e(title)+'</strong>'+(desc?'<p>'+e(desc)+'</p>':'')+action+'</div>';}
  function collectionPageV21(){
    if(collectionMode==='list')return collectionHeaderV21()+collectionNavV21()+'<div class="v21-page">'+(collectionsV21().length?collectionsV21().slice().sort((a,b)=>b.id-a.id).map(c=>{const items=linkedItemsV21(c),photo=collectionPhotosV21(c)[0]?.url,meta=c.kind==='trip'?dateLabel(c.startDate)+' – '+dateLabel(c.endDate):'덤프 '+items.posts.length+' · 일정 '+items.events.length+' · 할 일 '+items.tasks.length;return '<button class="v21-list-row" onclick="OD.collectionOpen('+c.id+')"><span class="v21-list-cover">'+(photo?'<img src="'+e(photo)+'" alt="" onerror="this.hidden=true">':icon(c.kind==='trip'?'pin':'grid'))+'</span><span class="v21-row-text"><strong>'+e(c.title)+'</strong><small>'+e(meta)+'</small></span>'+icon('right')+'</button>';}).join(''):collectionEmptyV21('아직 만든 모음이 없습니다','여행이나 관심 있는 주제로 모아보세요.','<button class="v21-action" onclick="OD.collectionForm()">'+icon('plus')+'모음 만들기</button>'))+'<p class="v21-connection-note">현재 모음과 여행 계획은 이 브라우저에 저장됩니다. 상대와 함께 편집하는 기능은 서버 연결 후 제공됩니다.</p></div>';
    const c=collectionByIdV21(activeCollectionId);if(!c){collectionMode='list';activeCollectionId=null;return collectionPageV21();}
    const sections=c.kind==='trip'?['계획','할 일','덤프','사진']:['덤프','사진','일정','할 일'];if(!sections.includes(collectionSection))collectionSection=sections[0];
    const title='<div class="v21-heading">'+btn('모음 목록','OD.collections()','left')+'<h1>'+e(c.title)+'</h1>'+btn('모음 설정','OD.collectionMenu()','more')+'</div>';
    const info=c.kind==='trip'?'<div class="v21-trip-summary"><p>'+e(dateLabel(c.startDate)+' – '+dateLabel(c.endDate))+' · '+daysV21(c.startDate,c.endDate).length+'일</p><button class="v21-action" onclick="OD.collectionCalendar()">'+icon('calendar')+(state.events.some(v=>v.id===c.eventId)?'달력에서 보기':'달력에 추가')+'</button></div>':'';
    const tabs='<div class="v21-section-tabs" role="tablist" aria-label="모음 내용">'+sections.map((s,i)=>'<button id="v21-tab-'+i+'" role="tab" aria-controls="v21-panel" aria-selected="'+(s===collectionSection)+'" onclick="OD.collectionSection(\''+s+'\')">'+s+'</button>').join('')+'</div>';
    return collectionHeaderV21()+'<div class="v21-page">'+title+info+tabs+'<div id="v21-panel" role="tabpanel" aria-labelledby="v21-tab-'+sections.indexOf(collectionSection)+'">'+collectionBodyV21(c)+'</div></div>';
  }
  function collectionBodyV21(c){const items=linkedItemsV21(c);
    if(collectionSection==='계획')return tripPlanV21(c);
    if(collectionSection==='사진'){const photos=collectionPhotosV21(c);return photos.length?'<div class="v21-photo-grid">'+photos.map(({url,p,index})=>'<button aria-label="'+e((p.text||'덤프')+' 사진 '+(index+1))+'" onclick="OD.collectionPhoto('+p.id+','+index+')"><img src="'+e(url)+'" loading="lazy" alt="'+e((p.location||'덤프')+' 사진 '+(index+1))+'" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="v21-photo-error" hidden>사진을 불러오지 못했어요</span></button>').join('')+'</div>':collectionEmptyV21('아직 사진이 없습니다','이 모음에 연결한 덤프의 사진이 표시됩니다.','<button class="v21-action" onclick="OD.collectionCreate(\'post\')">사진 올리기</button>');}
    const type=collectionSection==='덤프'?'post':collectionSection==='일정'?'event':'task';
    const add='<div class="v21-actions-line"><button class="v21-action" onclick="OD.collectionCreate(\''+type+'\')">'+icon('plus')+(type==='post'?'덤프 작성':type==='event'?'일정 등록':'할 일 추가')+'</button><button class="v21-action" onclick="OD.collectionLink(\''+type+'\')">기존 '+(type==='post'?'덤프':type==='event'?'일정':'할 일')+' 가져오기</button></div>';
    if(type==='post')return add+(items.posts.length?'<div class="v21-detail-feed">'+items.posts.map(postCard).join('')+'</div>':collectionEmptyV21('아직 연결한 덤프가 없습니다',''));
    if(type==='event')return add+(items.events.length?items.events.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(eventCard).join(''):collectionEmptyV21('아직 연결한 일정이 없습니다',''));
    return add+(items.tasks.length?items.tasks.slice().sort(compareTasks).map(({task,category})=>taskCard(task,category)).join(''):collectionEmptyV21('아직 연결한 할 일이 없습니다',''));
  }
  function tripPlanV21(c){const days=daysV21(c.startDate,c.endDate);if(!days.includes(tripDay))tripDay=days[0];const stops=c.stops.filter(s=>s.date===tripDay);
    return '<div class="v21-days" aria-label="여행 날짜">'+days.map((d,i)=>'<button aria-pressed="'+(d===tripDay)+'" onclick="OD.tripDay(\''+d+'\')"><strong>Day '+(i+1)+'</strong><small>'+Number(d.slice(5,7))+'.'+Number(d.slice(8))+'</small></button>').join('')+'</div><div class="v21-plan-date">'+e(taskDateLabel(tripDay))+'</div>'+(stops.length?stops.map((s,i)=>'<article class="v21-stop"><span class="v21-stop-number">'+String(i+1).padStart(2,'0')+'</span><div class="v21-stop-main"><button onclick="OD.tripStop('+s.id+')" aria-label="'+e(s.title)+' 수정">'+e(s.title)+'</button>'+(s.note?'<p>'+e(s.note)+'</p>':'')+'<a target="_blank" rel="noopener noreferrer" href="'+e(safeLinkV21(s.url)||'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s.title))+'">'+icon('pin')+(s.url?'링크 열기':'지도에서 검색')+'</a></div><div class="v21-reorder"><button '+(i===0?'disabled':'')+' aria-label="'+e(s.title)+' 위로 이동" onclick="OD.tripMove('+s.id+',-1)"><span class="v21-up">'+icon('left')+'</span></button><button '+(i===stops.length-1?'disabled':'')+' aria-label="'+e(s.title)+' 아래로 이동" onclick="OD.tripMove('+s.id+',1)"><span class="v21-down">'+icon('left')+'</span></button></div></article>').join(''):collectionEmptyV21('아직 정한 장소가 없습니다','방문할 장소를 순서대로 추가하세요.'))+'<button class="v21-action od-wide" onclick="OD.tripStop()">'+icon('plus')+'장소 추가</button>'+(c.note?'<p class="v21-note">'+e(c.note)+'</p>':'');
  }
  function openCollectionV21(n,section){const c=collectionByIdV21(n);if(!c){toast('삭제된 모음이에요.');return;}close(true);collectionMode='detail';activeCollectionId=c.id;collectionSection=section||(c.kind==='trip'?'계획':'덤프');tripDay=null;formCollectionContext=null;switchTo('our');$('main-viewport').scrollTop=0;}
  function collectionFormV21(n){const c=collectionByIdV21(n);collectionDraft=c?JSON.parse(JSON.stringify(c)):{kind:'collection',title:'',startDate:today(),endDate:today(),note:''};modalId=c?.id||null;formCollectionContext=null;renderCollectionFormV21();}
  function renderCollectionFormV21(){const c=collectionDraft;if(!c)return;const kind=c.kind==='trip';show(c.id?'모음 수정':'모음 만들기','<div class="od-stack">'+(!c.id?'<div class="od-field"><span>종류</span><div class="v21-collection-kind">'+['collection','trip'].map(t=>'<button type="button" aria-pressed="'+(c.kind===t)+'" onclick="OD.collectionKind(\''+t+'\')">'+icon(t==='trip'?'pin':'grid')+(t==='trip'?'여행':'모음')+'</button>').join('')+'</div></div>':'')+field('이름','collection-title',c.title,'text','maxlength="60" placeholder="'+(kind?'여행 이름':'모음 이름')+'"')+(kind?'<div class="od-grid2">'+dateField('시작일','date',c.startDate)+dateField('종료일','enddate',c.endDate)+'</div><p class="v21-form-help">여행 기간이 달력에도 하나의 일정으로 추가됩니다. 최대 31일까지 선택할 수 있어요.</p>':'')+'<label class="od-field"><span>메모 · 선택</span><textarea id="od-collection-note" maxlength="4000" rows="2" placeholder="예약 정보, 준비할 내용 등">'+e(c.note)+'</textarea></label><p id="v21-error" class="v21-form-error" role="alert"></p></div>',footer('저장','OD.saveCollection()'),'collection');}
  function collectionErrorV21(message){const el=$('v21-error');if(el)el.textContent=message;else toast(message);}
  function collectionKindV21(kind){if(!collectionDraft||collectionDraft.id||!['trip','collection'].includes(kind))return;collectionDraft.title=value('collection-title');collectionDraft.note=value('collection-note');collectionDraft.startDate=value('date')||collectionDraft.startDate;collectionDraft.endDate=value('enddate')||collectionDraft.endDate;collectionDraft.kind=kind;renderCollectionFormV21();if(collectionDraft.title||collectionDraft.note)$('od-sheet-body').dataset.dirty='true';}
  function tripEventV21(c){const old=state.events.find(v=>v.id===c.eventId);if(old){old.title=c.title;old.date=c.startDate;old.endDate=c.startDate===c.endDate?null:c.endDate;old.collectionId=c.id;old.version=(old.version||1)+1;return old;}
    if(state.events.length>=5000)throw Error('일정 보관 한도에 도달했어요.');const event={id:id(),title:c.title,date:c.startDate,endDate:c.startDate===c.endDate?null:c.endDate,allDay:true,time:'',endTime:'',createdBy:me(),createdAt:new Date().toISOString(),participants:[me()],subject:me(),subjectMemberId:me(),detailVisibility:'shared',lifecycle:'active',comments:[],participation:{},revisions:[],version:1,note:'',place:'',collectionId:c.id};state.events.push(event);c.eventId=event.id;return event;}
  function saveCollectionV21(){if(modalKind!=='collection'||!collectionDraft)return;const title=value('collection-title'),note=value('collection-note'),start=value('date'),end=value('enddate')||start,old=collectionDraft.id?collectionByIdV21(collectionDraft.id):null;
    if(!title||title.length>60||note.length>4000){collectionErrorV21('모음 이름은 1~60자로 입력해 주세요.');return;}if(collectionDraft.id&&!old){collectionErrorV21('원본 모음이 삭제되었어요.');return;}if(!old&&collectionsV21().length>=200){collectionErrorV21('모음은 최대 200개까지 만들 수 있어요.');return;}
    if(collectionDraft.kind==='trip'&&!daysV21(start,end).length){collectionErrorV21('여행 기간은 시작일부터 최대 31일로 선택해 주세요.');return;}if(old?.stops.some(s=>s.date<start||s.date>end)){collectionErrorV21('새 기간 밖에 장소가 있습니다. 장소 날짜를 먼저 바꿔 주세요.');return;}
    const c={...(old||{id:id(),createdBy:me(),createdAt:new Date().toISOString(),stops:[],eventId:null}),title,note,kind:collectionDraft.kind,startDate:collectionDraft.kind==='trip'?start:null,endDate:collectionDraft.kind==='trip'?end:null};
    if(c.kind==='trip'&&!state.events.some(v=>v.id===c.eventId)&&state.events.length>=5000){collectionErrorV21('일정 보관 한도에 도달했어요. 기존 일정을 정리해 주세요.');return;}
    if(!commit(()=>{state.collections=collectionsV21();if(old)state.collections[state.collections.indexOf(old)]=c;else state.collections.push(c);if(c.kind==='trip')tripEventV21(c);},'모음을 저장했어요.'))return;collectionDraft=null;openCollectionV21(c.id);
  }
  function reconcileCollectionsV21(before){const previous=JSON.parse(before);for(const c of collectionsV21()){if(c.kind!=='trip'||!c.eventId)continue;const v=state.events.find(v=>v.id===c.eventId),old=previous.events?.find(v=>v.id===c.eventId),oldCollection=previous.collections?.find(v=>v.id===c.id);if(!v){c.eventId=null;continue;}v.collectionId=c.id;if(old&&oldCollection&&c.title===oldCollection.title&&v.title!==old.title){if(v.title.length>60)throw Error('여행 제목 길이 오류');c.title=v.title;}if(old&&oldCollection&&c.startDate===oldCollection.startDate&&c.endDate===oldCollection.endDate&&(v.date!==old.date||v.endDate!==old.endDate)){const end=v.endDate||v.date;if(!daysV21(v.date,end).length||c.stops.some(s=>s.date<v.date||s.date>end))throw Error('여행 기간 오류');c.startDate=v.date;c.endDate=end;}}
    // Existing delete paths retain their behavior and cannot leave broken collection IDs.
    const ids=new Set(collectionsV21().map(c=>c.id));for(const item of [...state.posts,...state.events,...allTasks().map(x=>x.task)])if(item.collectionId!=null&&!ids.has(item.collectionId))item.collectionId=null;
  }
  function eventRangeAllowedV21(v,start,end){const c=v&&collectionsV21().find(c=>c.eventId===v.id);if(!c)return true;if(value('title').length>60){toast('여행 이름은 60자까지 입력해 주세요.');return false;}if(!daysV21(start,end).length){toast('연결된 여행 기간은 최대 31일로 선택해 주세요.');return false;}if(c.stops.some(s=>s.date<start||s.date>end)){toast('여행 장소가 새 기간 밖에 있어요. 모음에서 장소 날짜를 먼저 바꿔 주세요.');return false;}return true;}
  function collectionFieldV21(current){const selected=collectionByIdV21(current??formCollectionContext);return '<div class="od-field v21-collection-field"><span>모음 · 선택</span><input type="hidden" id="od-collection-id" value="'+(selected?.id||'')+'"><button type="button" onclick="OD.collectionPicker()"><span id="od-collection-label">'+e(selected?.title||'모음 없이 올리기')+'</span>'+icon('down')+'</button></div>';}
  function chosenCollectionV21(){const n=Number(value('collection-id'));return n&&collectionByIdV21(n)?n:null;}
  function collectionPickerV21(){if($('v21-picker'))return;const current=chosenCollectionV21(),layer=document.createElement('div');layer.id='v21-picker';layer.className='v21-picker-layer';layer.innerHTML='<section class="v21-picker-card" role="dialog" aria-modal="true" aria-labelledby="v21-picker-title"><header><strong id="v21-picker-title">모음 선택</strong>'+btn('모음 선택 닫기','OD.collectionPickerClose()','x')+'</header><div class="v21-picker-options">'+[{id:null,title:'선택 안 함'},...collectionsV21()].map(c=>'<button onclick="OD.collectionChoose('+(c.id||'null')+')" aria-pressed="'+(current===c.id)+'"><span>'+e(c.title)+'</span>'+(current===c.id?icon('check'):'')+'</button>').join('')+'</div></section>';$('od-overlay').querySelector('.od-sheet').inert=true;$('od-overlay').appendChild(layer);layer.querySelector('button').focus();layer.addEventListener('click',ev=>{if(ev.target===layer)closeCollectionPickerV21();});}
  function closeCollectionPickerV21(){const layer=$('v21-picker');if(!layer)return;layer.remove();const sh=$('od-overlay').querySelector('.od-sheet');if(sh)sh.inert=false;$('od-collection-label')?.parentElement.focus({preventScroll:true});}
  function collectionChooseV21(n){const c=collectionByIdV21(n);$('od-collection-id').value=c?.id||'';$('od-collection-label').textContent=c?.title||'모음 없이 올리기';$('od-sheet-body').dataset.dirty='true';closeCollectionPickerV21();}
  function collectionMenuV21(){const c=collectionByIdV21(activeCollectionId);if(!c)return;show('모음 설정','<button class="od-menu-item" onclick="OD.collectionForm('+c.id+')">'+icon('image')+'모음 수정</button><button class="od-menu-item od-danger" onclick="OD.collectionDelete('+c.id+')">'+icon('trash')+'모음 삭제</button>','','menu');}
  async function collectionDeleteV21(n){const c=collectionByIdV21(n);if(!c)return;const confirmed=await askConfirm({title:'모음을 삭제할까요?',message:'연결한 덤프, 일정, 할 일은 그대로 남습니다.',confirmLabel:'모음 삭제',tone:'danger'});if(!confirmed)return;if(commit(()=>{state.collections=collectionsV21().filter(c=>c.id!==n);},'모음을 삭제했어요.')){close(true);collectionMode='list';activeCollectionId=null;render();}}
  function collectionAddV21(){const c=collectionByIdV21(activeCollectionId);if(!c)return;show('모음에 추가',(c.kind==='trip'?'<button class="od-menu-item" onclick="OD.tripStop()">'+icon('pin')+'여행 장소</button>':'')+'<button class="od-menu-item" onclick="OD.collectionCreate(\'post\')">'+icon('image')+'덤프 작성</button><button class="od-menu-item" onclick="OD.collectionCreate(\'task\')">'+icon('todo')+'할 일 추가</button>'+(c.kind!=='trip'?'<button class="od-menu-item" onclick="OD.collectionCreate(\'event\')">'+icon('calendar')+'일정 등록</button>':''),'','menu');}
  function createInCollectionV21(type){const c=collectionByIdV21(activeCollectionId);if(!c||!['post','task','event'].includes(type))return;formCollectionContext=c.id;if(type==='post')post();else if(type==='task')taskForm();else{selected=c.startDate||today();eventForm();}}
  function tripStopV21(n){const c=collectionByIdV21(activeCollectionId);if(!c||c.kind!=='trip')return;const s=n?c.stops.find(s=>s.id===n):null;if(n&&!s){toast('삭제된 장소예요.');return;}stopDraft={collectionId:c.id,id:s?.id||null};show(s?'장소 수정':'장소 추가','<div class="od-stack">'+field('장소','stop-title',s?.title||'','text','maxlength="100" placeholder="장소 이름"')+dateField('방문일','date',s?.date||tripDay||c.startDate,'min="'+c.startDate+'" max="'+c.endDate+'"')+field('링크 · 선택','stop-url',s?.url||'','url','maxlength="2000" placeholder="지도, 숙소 또는 예약 링크"')+'<label class="od-field"><span>메모 · 선택</span><textarea id="od-stop-note" rows="2" maxlength="1000" placeholder="예약 시간, 확인할 내용 등">'+e(s?.note||'')+'</textarea></label><p id="v21-error" class="v21-form-error" role="alert"></p>'+(s?'<button class="v21-action od-danger" onclick="OD.tripStopDelete('+s.id+')">장소 삭제</button>':'')+'</div>',footer('저장','OD.tripStopSave()'),'tripStop');}
  function saveTripStopV21(){if(modalKind!=='tripStop'||!stopDraft)return;const c=collectionByIdV21(stopDraft.collectionId),title=value('stop-title'),date=value('date'),url=safeLinkV21(value('stop-url')),note=value('stop-note'),old=c?.stops.find(s=>s.id===stopDraft.id);if(!c||stopDraft.id&&!old){collectionErrorV21('원본 모음이나 장소가 삭제되었어요.');return;}if(!title||title.length>100||note.length>1000){collectionErrorV21('장소 이름과 메모를 확인해 주세요.');return;}if(!validISODate(date)||date<c.startDate||date>c.endDate){collectionErrorV21('여행 기간 안의 날짜를 선택해 주세요.');return;}if(url===null){collectionErrorV21('링크는 https://로 시작하는 주소를 입력해 주세요.');return;}if(!old&&c.stops.length>=300){collectionErrorV21('장소는 최대 300개까지 추가할 수 있어요.');return;}const data={id:old?.id||id(),title,date,url,note};if(commit(()=>{if(old)Object.assign(old,data);else c.stops.push(data);},'장소를 저장했어요.')){stopDraft=null;close(true);tripDay=date;collectionSection='계획';render();}}
  function moveTripStopV21(n,delta){const c=collectionByIdV21(activeCollectionId),s=c?.stops.find(s=>s.id===n);if(!s||![-1,1].includes(delta))return;const daily=c.stops.filter(v=>v.date===s.date),index=daily.indexOf(s),other=daily[index+delta];if(!other)return;if(commit(()=>{const a=c.stops.indexOf(s),b=c.stops.indexOf(other);[c.stops[a],c.stops[b]]=[c.stops[b],c.stops[a]];})){render();$('main-viewport').querySelector('.v21-stop-main button[onclick="OD.tripStop('+n+')"]')?.focus({preventScroll:true});}}
  async function deleteTripStopV21(n){const c=collectionByIdV21(activeCollectionId);if(!c||!c.stops.some(s=>s.id===n))return;if(await askConfirm({title:'장소를 삭제할까요?',message:'이 여행 계획에서 삭제됩니다.',confirmLabel:'삭제',tone:'danger'})&&commit(()=>{c.stops=c.stops.filter(s=>s.id!==n);},'장소를 삭제했어요.')){close(true);render();}}
  function collectionCalendarV21(){const c=collectionByIdV21(activeCollectionId);if(!c||c.kind!=='trip')return;let v=state.events.find(v=>v.id===c.eventId);if(!v){if(state.events.length>=5000){toast('일정 보관 한도에 도달했어요.');return;}if(!commit(()=>{v=tripEventV21(c);},'달력에 추가했어요.'))return;}close(true);selected=c.startDate;month=selected.slice(0,7);calFilter='전체';switchTo('calendar');$('od-event-'+v.id)?.scrollIntoView({block:'start',behavior:'instant'});}
  function collectionReturnV21(item){const c=collectionByIdV21(item?.collectionId);if(c)$('od-sheet-body')?.insertAdjacentHTML('beforeend','<button class="v21-return" onclick="OD.collectionOpen('+c.id+')">'+icon('grid')+e(c.title)+' 모음 보기'+icon('right')+'</button>');}
  function linkCollectionV21(type){if(!['post','event','task'].includes(type)||!collectionByIdV21(activeCollectionId))return;linkContext={collectionId:activeCollectionId,type};show('기존 '+({post:'덤프',event:'일정',task:'할 일'}[type])+' 가져오기','<input id="v21-search" class="v21-record-search" placeholder="검색" aria-label="가져올 항목 검색" maxlength="100" oninput="OD.collectionSearch()"><div id="v21-records"></div><p class="v21-record-status">원본은 기존 화면에도 그대로 남습니다.</p>',footer('완료','OD.close(true)'),'collectionLinks');renderLinkRecordsV21();}
  function renderLinkRecordsV21(){if(!linkContext)return;const c=collectionByIdV21(linkContext.collectionId);if(!c)return;const type=linkContext.type,q=($('v21-search')?.value||'').trim().toLowerCase();const source=type==='post'?state.posts.filter(v=>v.author===me()||isCoupleConnected()):type==='event'?state.events.filter(v=>canSeeDetails(v)&&!isHiddenFromMe(v)&&!collectionsV21().some(c=>c.eventId===v.id)):allTasks().map(x=>x.task);const eligible=source.filter(v=>v.collectionId==null||v.collectionId===c.id),rows=eligible.filter(v=>(v.text||v.title||'사진').toLowerCase().includes(q));$('v21-records').innerHTML=rows.length?rows.slice(0,100).map(v=>'<button class="v21-record-button" aria-pressed="'+(v.collectionId===c.id)+'" onclick="OD.collectionToggleLink('+v.id+')">'+avatar(v.author||v.createdBy||me(),true)+'<span class="v21-row-text"><strong>'+e(v.text||v.title||'사진')+'</strong><small>'+e(v.date?dateLabel(v.date):v.targetDate?dateLabel(v.targetDate):'')+'</small></span>'+icon(v.collectionId===c.id?'check':'plus')+'</button>').join('')+(rows.length>100?'<p class="v21-record-status">처음 100개를 표시합니다. 검색으로 항목을 찾아 주세요.</p>':''):collectionEmptyV21('가져올 항목이 없습니다',q?'검색어를 바꿔보세요.':'다른 모음에 넣지 않은 항목을 가져올 수 있습니다.');}
  function toggleLinkV21(n){if(!linkContext)return;const c=collectionByIdV21(linkContext.collectionId),type=linkContext.type,item=(type==='post'?state.posts:type==='event'?state.events:allTasks().map(x=>x.task)).find(v=>v.id===n);if(!c||!item||item.collectionId!=null&&item.collectionId!==c.id)return;if(type==='event'&&(isHiddenFromMe(item)||!canSeeDetails(item)||collectionsV21().some(c=>c.eventId===item.id)))return;if(commit(()=>{item.collectionId=item.collectionId===c.id?null:c.id;})){render();renderLinkRecordsV21();$('v21-records')?.querySelector('button[onclick="OD.collectionToggleLink('+n+')"]')?.focus({preventScroll:true});}}
  function collectionPhotoV21(n,index){const p=state.posts.find(p=>p.id===n),c=collectionByIdV21(activeCollectionId);if(!p||p.collectionId!==c?.id)return;const media=p.media?.length?p.media:p.photoUrl?[p.photoUrl]:[],url=media[index];if(!url)return;show('사진','<div class="v21-gallery-view"><img src="'+e(url)+'" alt="'+e(p.text||'덤프 사진')+'"><div class="od-row">'+avatar(p.author,true)+'<strong>'+e(nicknameOf(p.author))+'</strong></div>'+(p.text?'<p>'+e(p.text)+'</p>':'')+'</div>',footer('본문과 댓글','OD.comments('+p.id+')'),'collectionPhoto');}
  const basePostV21=post,baseEventFormV21=eventForm,baseTaskFormV21=taskForm,baseSavePostV21=savePost,baseSaveEventV21=saveEvent,baseSaveTaskV21=saveTask,baseEventDetailV21=eventDetail,baseTaskDetailV21=taskDetail,baseCloseV21=close;
  function validCollectionSelectionV21(){const n=value('collection-id');if(n&&!collectionByIdV21(Number(n))){toast('선택한 모음이 삭제되었어요. 모음을 다시 선택해 주세요.');return false;}return true;}
  savePost=async function(){if(!validCollectionSelectionV21())return;const context=formCollectionContext,target=chosenCollectionV21();await baseSavePostV21();if(context&&$('od-overlay').hidden){if(target&&collectionByIdV21(target)){collectionMode='detail';activeCollectionId=target;collectionSection='덤프';switchTo('our');}else{resetFeedV21();render();}}if($('od-overlay').hidden)formCollectionContext=null;};
  saveEvent=function(){if(!validCollectionSelectionV21())return;const context=formCollectionContext,target=chosenCollectionV21();baseSaveEventV21();if(context&&modalKind!=='event'){if(target&&collectionByIdV21(target)){collectionMode='detail';activeCollectionId=target;collectionSection=collectionByIdV21(target).kind==='trip'?'계획':'일정';switchTo('our');}else resetFeedV21();}if($('od-overlay').hidden)formCollectionContext=null;};
  saveTask=function(){if(!validCollectionSelectionV21())return;const context=formCollectionContext,target=chosenCollectionV21();baseSaveTaskV21();if(context&&$('od-overlay').hidden){if(target&&collectionByIdV21(target)){collectionMode='detail';activeCollectionId=target;collectionSection='할 일';switchTo('our');}else resetFeedV21();}if($('od-overlay').hidden)formCollectionContext=null;};
  eventDetail=function(n){baseEventDetailV21(n);collectionReturnV21(state.events.find(v=>v.id===n));};taskDetail=function(n){baseTaskDetailV21(n);collectionReturnV21(taskById(n)?.task);};
  close=async function(force=false){if($('v21-picker')&&!force){closeCollectionPickerV21();return;}await baseCloseV21(force);if($('od-overlay').hidden)formCollectionContext=null;};
  const baseRenderV21=render;render=function(){const days=$('main-viewport')?.querySelector('.v21-days'),dayScroll=days?.scrollLeft;baseRenderV21();const current=$('main-viewport')?.querySelector('.v21-days');if(current&&dayScroll!=null)current.scrollLeft=dayScroll;};
  const resetFeedV21=()=>{collectionMode='feed';activeCollectionId=null;};
  const myPostsV21=OD.myPosts,mySavedV21=OD.mySaved,readNotifV21=OD.readNotif,filterFeedV21=OD.filterFeed,savedFeedV21=OD.savedFeed,beginGuideV21=OD.beginGuide,resumeGuideV21=OD.resumeGuide;
  Object.assign(OD,{close,savePost,saveEvent,saveTask,eventDetail,taskDetail,
    post:n=>{formCollectionContext=tab==='our'&&collectionMode==='detail'?activeCollectionId:null;basePostV21(n);},event:(n,t)=>{formCollectionContext=tab==='our'&&collectionMode==='detail'?activeCollectionId:null;baseEventFormV21(n,t);const c=collectionsV21().find(c=>c.eventId===n);if(c){$('od-title').maxLength=60;const f=$('od-collection-id')?.parentElement;const button=f?.querySelector('button');if(button){button.removeAttribute('onclick');button.disabled=true;button.title='여행 기간 일정은 해당 여행 모음에 연결됩니다.';}}},task:(n,p)=>{formCollectionContext=tab==='our'&&collectionMode==='detail'?activeCollectionId:null;baseTaskFormV21(n,p);},
    myPosts:()=>{resetFeedV21();myPostsV21();},mySaved:()=>{resetFeedV21();mySavedV21();},readNotif:n=>{resetFeedV21();return readNotifV21(n);},filterFeed:f=>{resetFeedV21();filterFeedV21(f);},savedFeed:()=>{resetFeedV21();savedFeedV21();},
    beginGuide:()=>{resetFeedV21();return beginGuideV21();},resumeGuide:()=>{resetFeedV21();return resumeGuideV21();},
    collections:()=>{close(true);collectionMode='list';activeCollectionId=null;formCollectionContext=null;switchTo('our');$('main-viewport').scrollTop=0;},collectionsFeed:()=>{resetFeedV21();switchTo('our');$('main-viewport').scrollTop=0;},
    collectionOpen:openCollectionV21,collectionForm:collectionFormV21,collectionKind:collectionKindV21,saveCollection:saveCollectionV21,collectionMenu:collectionMenuV21,collectionDelete:collectionDeleteV21,collectionAdd:collectionAddV21,collectionCreate:createInCollectionV21,collectionPicker:collectionPickerV21,collectionPickerClose:closeCollectionPickerV21,collectionChoose:collectionChooseV21,collectionLink:linkCollectionV21,collectionSearch:renderLinkRecordsV21,collectionToggleLink:toggleLinkV21,collectionCalendar:collectionCalendarV21,collectionPhoto:collectionPhotoV21,
    collectionSection:s=>{const c=collectionByIdV21(activeCollectionId),allowed=c?.kind==='trip'?['계획','할 일','덤프','사진']:['덤프','사진','일정','할 일'];if(!allowed.includes(s))return;collectionSection=s;render();},
    tripDay:d=>{const c=collectionByIdV21(activeCollectionId);if(c&&daysV21(c.startDate,c.endDate).includes(d)){tripDay=d;render();}},tripStop:tripStopV21,tripStopSave:saveTripStopV21,tripMove:moveTripStopV21,tripStopDelete:deleteTripStopV21
  });
