const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
let html=fs.readFileSync('outputs/index0922testv21.html','utf8');
const patch=(a,b)=>{if(!html.includes(a))throw Error('Missing v22 anchor: '+a.slice(0,130));html=html.replace(a,b);};
function functionSource(source,name){const m=new RegExp('(?:async\\s+)?function\\s+'+name+'\\s*\\(').exec(source);if(!m)throw Error('Missing function '+name);let end=source.indexOf('\n',m.index);while(end>=0){const s=source.slice(m.index,end).trim();try{new vm.Script('('+s+')');return s;}catch{}end=source.indexOf('\n',end+1);}throw Error('Cannot parse '+name);}
const replaceFunction=(name,source)=>patch(functionSource(html,name),source);
const ui=fs.readFileSync('work/gallery-location-v22.js','utf8').replace("return header('일정')+","return collectionHeaderV21()+");
patch('    function checkBackup(raw){',functionSource(ui,'validCoordinatesV22')+'\n'+functionSource(ui,'validateUiV22')+'\n    function checkBackup(raw){');
patch('      validateCollectionsV21(raw);','      validateCollectionsV21(raw);validateUiV22(raw);');
patch('    window.state = normalizeState(readStoredState());','    window.state = normalizeState(readStoredState());\n    if(window.odStorageIssue){Object.assign(window.state,{posts:[],events:[],todoCategories:[{id:"wishlist",title:"할 일",items:[]}],collections:[],notifications:[],joinRequests:[],dailyMarkers:[],cycleMarkers:[],heroPhoto:null,heroTitle:"",heroSubtitle:"",anniversary:null,firstMetDate:null,memberProfiles:{"준영":{nickname:"나"},"아정":{}},profiles:{},noSampleProfile:true,connection:{status:"unconnected"}}); }');
patch("tab==='calendar'?calendar():tab==='todo'", "tab==='calendar'?calendarPageV22():tab==='chat'?chatPageV22():tab==='todo'");
patch("['calendar','일정','calendar'],['todo'", "['calendar','일정','calendar'],['chat','톡','comment'],['todo'");
patch("const unread=connectionNotifications().filter", "const chatUnread=chatUnreadV22();\n    const unread=connectionNotifications().filter");
patch("${t==='account'?'<span id=\"od-nav-unread\"", "${t==='chat'?'<span id=\"od-chat-unread\" class=\"od-badge\" aria-label=\"읽지 않은 예시 메시지 '+chatUnread+'개\" '+(chatUnread?'':'hidden')+'>'+(chatUnread>99?'99+':chatUnread)+'</span>':t==='account'?'<span id=\"od-nav-unread\"");
patch('    guideRefresh();\n  }\n  function updateMoreLabels()',"    guideRefresh();if(tab==='chat')requestAnimationFrame(()=>{if(tab==='chat')chatRenderAfterV22();});\n  }\n  function updateMoreLabels()");
replaceFunction('switchTo',"function switchTo(t){if(!['our','calendar','chat','todo','account','notif'].includes(t))return;scrolls[tab]=$('main-viewport').scrollTop;tab=t;render();$('main-viewport').scrollTop=scrolls[t]||0;if(t==='chat')requestAnimationFrame(()=>{if(tab==='chat')OD.chatEnter();});}");
replaceFunction('feed',"function feed(){const posts=filteredPostsV22();return header('덤프')+feedToolbar()+feedNavV22()+(feedModeV22==='photos'?galleryV22(posts):posts.length?posts.map(postCard).join(''):feedFilter==='전체'&&state.posts.length===0?onboardingEmpty():('<div class=\"od-empty\">'+icon('image')+'<strong>'+(feedFilter==='저장'?'저장한 덤프가 없습니다':'아직 덤프가 없습니다')+'</strong><button class=\"od-text-action\" onclick=\"OD.filterFeed(&quot;전체&quot;)\">전체 덤프</button></div>'));}");
replaceFunction('feedToolbar',"function feedToolbar(){const author=feedFilter==='저장'?lastAuthorFilter:feedFilter,faces=['준영','아정'].includes(author)?avatar(author,true):avatarPair(connectionMembers());return '<div class=\"od-filter-fixed\"><button class=\"od-cal-filter\" aria-label=\"작성자 필터\" aria-haspopup=\"dialog\" onclick=\"OD.peoplePicker(\\'our\\')\">'+faces+'<strong>'+e(['전체','함께'].includes(author)?author:nicknameOf(author))+'</strong>'+icon('down')+'</button><button class=\"od-icon\" aria-label=\"'+(feedFilter==='저장'?'저장한 덤프 닫기':'저장한 덤프')+'\" aria-pressed=\"'+(feedFilter==='저장')+'\" onclick=\"OD.savedFeed()\">'+icon('bookmark')+'</button></div>';}");
patch("const current=kind==='our'?feedFilter:kind==='calendar'", "const current=kind==='our'?(feedFilter==='저장'?lastAuthorFilter:feedFilter):kind==='calendar'");
patch("if(kind==='our'){feedFilter=w;lastAuthorFilter=w;}","if(kind==='our'){const saved=feedFilter==='저장';lastAuthorFilter=w;feedFilter=saved?'저장':w;}");
patch("${field('장소','location',p?.location||p?.meta?.spot||'','text','maxlength=\"120\" placeholder=\"장소 이름 입력 (선택사항)\"')}","${locationFieldV22(p)}");
patch('if(photoBusy||posting||modalKind!==\'post\')return;',"if(photoBusy||posting||modalKind!=='post')return;if(locationBusyV22){toast('위치 확인 후 게시해 주세요.');return;}");
patch('data={text,location,collectionId:', 'data={text,location,coordinates:locationDraftV22?{...locationDraftV22}:null,collectionId:');
patch('<span class="od-feed-location">${e(p.location||p.meta?.spot||\'\')}</span>', '<span class="od-feed-location">${locationTagV22(p)}</span>');
patch('<div class="od-meta">${e(p.location)}</div>', '<div class="od-meta">${locationTagV22(p)}</div>');
patch("close(true);feedFilter='전체';lastAuthorFilter='전체';switchTo('our');", "close(true);feedModeV22='feed';feedFilter='전체';lastAuthorFilter='전체';switchTo('our');");
replaceFunction('collectionFieldV21',"function collectionFieldV21(current){const selected=collectionByIdV21(current??formCollectionContext);return '<input type=\"hidden\" id=\"od-collection-id\" value=\"'+(selected?.id||'')+'\">';}");
replaceFunction('collectionReturnV21',"function collectionReturnV21(item){const c=collectionByIdV21(item?.collectionId);if(c?.kind==='trip')$('od-sheet-body')?.insertAdjacentHTML('beforeend','<button class=\"v21-return\" onclick=\"OD.collectionOpen('+c.id+')\">'+icon('calendar')+e(c.title)+' 여행 계획'+icon('right')+'</button>');}");
replaceFunction('collectionHeaderV21',"function collectionHeaderV21(){return header('일정').replace(btn('일정 등록','OD.event()','plus'),'');}");
patch("selected=c.startDate;month=selected.slice(0,7);calFilter='전체';switchTo('calendar');", "selected=c.startDate;month=selected.slice(0,7);calFilter='전체';resetFeedV21();switchTo('calendar');");
const originalPage=functionSource(html,'collectionPageV21');
patch(originalPage,originalPage.replace("if(collectionMode==='list')return collectionHeaderV21()+collectionNavV21()", "if(collectionMode==='list')return tripListV22();\n    if(false)return collectionHeaderV21()+collectionNavV21()").replace("btn('모음 목록','OD.collections()'","btn('여행 목록','OD.trips()'").replace("btn('모음 설정'","btn('여행 설정'").replace("aria-label=\"모음 내용\"","aria-label=\"여행 내용\"").replace("return collectionHeaderV21()+","return collectionHeaderV21()+"));
// Only travel plans keep the v21 linking machinery. Ordinary posts/photos never require it.
const start=html.indexOf('  // v21: optional collections'),end=html.indexOf('  // New UI is the sole screen renderer;',start);
let collectionBlock=html.slice(start,end).replaceAll("switchTo('our')","switchTo('calendar')").replaceAll("tab==='our'&&collectionMode==='detail'","tab==='calendar'&&collectionMode==='detail'");
collectionBlock=collectionBlock.replaceAll("'모음 수정'","'여행 수정'").replaceAll("'모음 만들기'","'여행 만들기'").replaceAll("'모음 이름은 1~60자로 입력해 주세요.'","'여행 이름은 1~60자로 입력해 주세요.'").replaceAll("'모음을 저장했어요.'","'여행 계획을 저장했어요.'").replaceAll("'모음 설정'","'여행 설정'").replaceAll('모음 수정</button>','여행 수정</button>').replaceAll('모음 삭제</button>','여행 삭제</button>').replaceAll("title:'모음을 삭제할까요?'","title:'여행 계획을 삭제할까요?'");
patch(html.slice(start,end),collectionBlock);
patch("const f=$('od-collection-id')?.parentElement;const button=f?.querySelector('button');if(button){button.removeAttribute('onclick');button.disabled=true;button.title='여행 기간 일정은 해당 여행 모음에 연결됩니다.';}","");
// The kinds selector is gone: new plans are always trips.
patch("{kind:'collection',title:'',startDate:today()", "{kind:'trip',title:'',startDate:today()");
const oldForm=functionSource(html,'renderCollectionFormV21');
patch(oldForm,oldForm.replace("+(!c.id?'<div class=\"od-field\"><span>종류</span>","+(false?'<div class=\"od-field\"><span>종류</span>"));
patch("${peopleToolbar('calendar',calFilter)}<section", "${peopleToolbar('calendar',calFilter)}<div class=\"v22-trip-entry\"><button onclick=\"OD.trips()\">${icon('pin')}여행 계획${icon('right')}</button></div><section");
patch('<button class="od-menu-item" onclick="OD.resetPreview()">샘플로 다시 시작</button>','');
patch("    if(posting&&!force)return;","    if($('v22-map-layer')&&!force){closeMapV22();return;}\n    if(posting&&!force)return;");
patch("if(window.odConflict)syncExternal();guideRefresh();","if(window.odConflict)syncExternal();guideRefresh();if(tab==='chat')requestAnimationFrame(chatEnterV22);");
patch('<strong>댓글을 남겨보세요</strong><p>서로의 하루에 한마디를 더해요.</p>','<strong>아직 댓글이 없습니다</strong>');
patch("dump-onboarding-preview.html?v=20'","dump-onboarding-preview.html?v=22'");
patch('  // New UI is the sole screen renderer;',ui+'\n'+fs.readFileSync('work/chat-v22.js','utf8')+'\n  // New UI is the sole screen renderer;');
patch('</head>','<meta name="dump-version" content="22"><style id="dump-ui-v22">'+fs.readFileSync('work/gallery-location-v22.css','utf8')+'\n'+fs.readFileSync('work/chat-v22.css','utf8')+'</style>\n</head>');
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
fs.writeFileSync('outputs/index0922testv22.html',html);fs.writeFileSync('outputs/dump-final.html',html);
fs.writeFileSync('outputs/dump-onboarding-preview.html',html.replaceAll("'our_days_app_v6_state'","'dump_onboarding_preview_v20_state'").replaceAll("'our_days_device_user'","'dump_onboarding_preview_v20_user'"));
console.log('v22 built '+crypto.createHash('sha256').update(html).digest('hex'));
